// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArzAblGffXoqYorBRo4Jyu8IYGXxtJjYk',
    appId: '1:159328590842:web:eae9fe61cd6249e5882243',
    messagingSenderId: '159328590842',
    projectId: 'somativasenai',
    authDomain: 'somativasenai.firebaseapp.com',
    storageBucket: 'somativasenai.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmyomIwGx389NYWLAZhyWyn_Qd6JOK7cc',
    appId: '1:159328590842:android:fc946ee6095fbfb3882243',
    messagingSenderId: '159328590842',
    projectId: 'somativasenai',
    storageBucket: 'somativasenai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2kT2zJMzYOtfIxeVM-fwJ4rqB_PmGcyM',
    appId: '1:159328590842:ios:87e83cfe77b7d5ef882243',
    messagingSenderId: '159328590842',
    projectId: 'somativasenai',
    storageBucket: 'somativasenai.appspot.com',
    iosBundleId: 'com.example.qrCodeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2kT2zJMzYOtfIxeVM-fwJ4rqB_PmGcyM',
    appId: '1:159328590842:ios:87e83cfe77b7d5ef882243',
    messagingSenderId: '159328590842',
    projectId: 'somativasenai',
    storageBucket: 'somativasenai.appspot.com',
    iosBundleId: 'com.example.qrCodeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArzAblGffXoqYorBRo4Jyu8IYGXxtJjYk',
    appId: '1:159328590842:web:8383e09a38fab9f5882243',
    messagingSenderId: '159328590842',
    projectId: 'somativasenai',
    authDomain: 'somativasenai.firebaseapp.com',
    storageBucket: 'somativasenai.appspot.com',
  );
}
